name: Cypress Cloud

on:
  workflow_dispatch:
    inputs:
      spec:
        description: Run by cypress command line
        default: cypres/e2e/*
        
jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0
        
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.8
        with:
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.events.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: 6ff9fcd2-91d6-479b-9c7c-cf02f604a36f
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
